apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-gateway
  namespace: jobportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: ahdaan/jobportal-gateway:v6
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: jobportal-gateway-config
            - secretRef:
                name: jobportal-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: jobportal
spec:
  selector:
    app: gateway  # This should match the labels of the pods serving the gateway
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091  # This should match the port exposed by the container
  type: ClusterIP  # Ensure the service type is appropriate