apiVersion: v1
kind: Secret
metadata:
  name: jobportal-secrets
  namespace: jobportal
type: Opaque
stringData:
  PASSWORD: "uftc lvzc wvcq azzq"
  LINKEDIN_CLIENT_SECRET: "oCEcexzTQHnZhYlR"
  SECRETACCESSKEY: "IdNUKLfI2558r0Gs6OmVqNO4Foox79fGAbmzzRLY"
  RAZORPAYSECRET: "Zl9DwhVSQJzyKRfQri3h4h37"
  DBURL: "postgres://postgres:2211@postgres:5432/jobportal?sslmode=disable"