FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o job ./cmd/job

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/job .
COPY --from=builder /app/logging ./logging
COPY --from=builder /app/logs ./logs
COPY .env . 

RUN mkdir -p /root/logs

EXPOSE 9001

CMD ["./job"]