FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o newsletter ./cmd/newsletter

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/newsletter .
COPY --from=builder /app/logging ./logging
COPY --from=builder /app/logs ./logs
COPY .env . 

RUN mkdir -p /root/logs

EXPOSE 9003

CMD ["./newsletter"]