FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o newsletter ./cmd/newsletter

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/newsletter .
COPY .env . 

EXPOSE 9003

CMD ["./newsletter"]