FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./cmd/gateway

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/gateway .
COPY --from=builder /app/internal/gateway/static ./internal/gateway/static
COPY --from=builder /app/internal/gateway/template ./internal/gateway/template
COPY .env . 

EXPOSE 9091

CMD ["./gateway"]