FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o user ./cmd/user

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/user .
COPY .env . 

EXPOSE 9002

CMD ["./user"]